### ISSUE TITLE
bug: useSearchParams() should be wrapped in a suspense boundary

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [aidenybai/react-scan#102]
In Next.js the component can't be rendered without wrapping it inside a suspense boundary:

```
 ⨯ useSearchParams() should be wrapped in a suspense boundary at page "/404". Read more: https://nextjs.org/docs/messages/missing-suspense-with-csr-bailout
    at i (/Users/dev/WebstormProjects/chat-io/.next/server/chunks/49.js:1:824)
    at Module.d (/Users/dev/WebstormProjects/chat-io/.next/server/chunks/49.js:1:5051)
    at q (/Users/dev/WebstormProjects/chat-io/.next/server/chunks/389.js:43:5259)
    at t.Monitoring (/Users/dev/WebstormProjects/chat-io/.next/server/chunks/389.js:43:5780)
    at nO (/Users/dev/WebstormProjects/chat-io/node_modules/.pnpm/next@15.1.0_@babel+core@7.26.0_@opentelemetry+api@1.9.0_babel-plugin-react-compiler@19.0.0-be_br3k3uwzqc3nf552se5nt2li2y/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:20:45959)
    at nI (/Users/dev/WebstormProjects/chat-io/node_modules/.pnpm/next@15.1.0_@babel+core@7.26.0_@opentelemetry+api@1.9.0_babel-plugin-react-compiler@19.0.0-be_br3k3uwzqc3nf552se5nt2li2y/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:20:47734)
    at nI (/Users/dev/WebstormProjects/chat-io/node_modules/.pnpm/next@15.1.0_@babel+core@7.26.0_@opentelemetry+api@1.9.0_babel-plugin-react-compiler@19.0.0-be_br3k3uwzqc3nf552se5nt2li2y/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:20:62515)
    at nL (/Users/dev/WebstormProjects/chat-io/node_modules/.pnpm/next@15.1.0_@babel+core@7.26.0_@opentelemetry+api@1.9.0_babel-plugin-react-compiler@19.0.0-be_br3k3uwzqc3nf552se5nt2li2y/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:20:65533)
    at nN (/Users/dev/WebstormProjects/chat-io/node_modules/.pnpm/next@15.1.0_@babel+core@7.26.0_@opentelemetry+api@1.9.0_babel-plugin-react-compiler@19.0.0-be_br3k3uwzqc3nf552se5nt2li2y/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:20:63164)
    at nB (/Users/dev/WebstormProjects/chat-io/node_modules/.pnpm/next@15.1.0_@babel+core@7.26.0_@opentelemetry+api@1.9.0_babel-plugin-react-compiler@19.0.0-be_br3k3uwzqc3nf552se5nt2li2y/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:20:68946)
Error occurred prerendering page "/_not-found". Read more: https://nextjs.org/docs/messages/prerender-error
Export encountered an error on /_not-found/page: /_not-found, exiting the build.
 ⨯ Static worker exited with code: 1 and signal: null
 ```

**Comment by RobPruzan** [comment]
Fixed in latest

`npm install react-scan@0.0.43`
