### ISSUE TITLE
HTMLElement is not defined

### ISSUE THREAD

**Issue by khashashin** [aidenybai/react-scan#35]
I have vite SSR and I saw that it has issues with ssr according to the following issue https://github.com/aidenybai/react-scan/issues/30 however there are examples for next.js app. I tried to do the trick as in the above issue but to no success

```
import '@/i18n';
import '@/axios';
import { BrowserRouter, Navigate, Route, Routes, useLocation } from 'react-router-dom';
import { StaticRouter } from 'react-router-dom/server';
import Home from '@/pages/Home/Home';
import { THEME_ID, ThemeProvider } from '@mui/material';
import PageNotFound from '@/pages/PageNotFound';
import { scan } from 'react-scan';

...
function Main() {
...
  useEffect(() => {
    scan({
      enabled: true,
      log: true,
      includeChildren: true,
      report: true,
    });
  }, []);
...
  return ();
}
```

```
ReferenceError: HTMLElement is not defined
    at file:///C:/Users/khash/Development/ebl-waermecheck/node_modules/react-scan/dist/index.mjs:1:9735
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async nodeImport (file:///C:/Users/khash/Development/ebl-waermecheck/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:53045:15)
    at async ssrImport (file:///C:/Users/khash/Development/ebl-waermecheck/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:52903:16)
    at async eval (C:/Users/khash/Development/ebl-waermecheck/src/Main.tsx:11:31)
    at async instantiateModule (file:///C:/Users/khash/Development/ebl-waermecheck/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:52961:5)
```

**Comment by aidenybai** [comment]
fixed! will be pushed in next release (@khashashin)

**Comment by Victor1890** [comment]
Please, close this issue 🤔
